# Generated by Django 4.1 on 2024-03-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatinstruction",
            name="instruction",
            field=models.TextField(
                default="A dialog, where User interacts with AI. AI is helpful, kind, obedient, \n    honest, and knows its own limits. User: Hello, AI. AI: Hello! How can I assist you today?"
            ),
        ),
    ]
